### ISSUE TITLE
Not Accurate Value

### ISSUE THREAD

**Issue by dotxzxc** [alexdev03/BuyCraftAPI#1]
When I try to get the value of the total earnings monthly and current month, the value is not accurate.

I'm using the Denizen plugin to narrate the value of a placeholder.
https://cdn.discordapp.com/attachments/740938529290453059/845628843716902922/a_bug_maybe.gif

**Comment by dotxzxc** [comment]
https://cdn.discordapp.com/attachments/740938529290453059/845632634100252732/a_bug_maybe_2.gif

**Comment by alexdev03** [comment]
I suggest you to use /papi parse me %placeholder% to test. Do you know the difference between monthly and current month?

**Comment by dotxzxc** [comment]
Yep, I know the difference and it parsed the same value using /papi parse me command.

**Comment by alexdev03** [comment]
Check in the config if there are all the payments and no duplicates.
