### ISSUE TITLE
Recent Name not working

### ISSUE THREAD

**Issue by belphegorspn** [alexdev03/BuyCraftAPI#2]
Hey! I've been using your placeholder api for awhile now. It works as it should except for the recent payment %buycraftAPI_recent_name_<number>% it displays a very old payment. 

Another thing is when I try to use %buycraftAPI_vault_recent_name_<number>%, it completely breaks all the placeholders I use.
![2022-08-06_01 57 39](https://user-images.githubusercontent.com/66054833/183134156-3b337e03-beb8-4405-8e4b-b9d8d9c2ed62.png)

**Comment by alexdev03** [comment]
Sorry but I can't update the plugin. Now I'm a paid developer and working on a free plugin would waste my time.

**Comment by belphegorspn** [comment]
Alright, I will be using it as long as I can. Thank you and best of luck with your work!

**Comment by alexdev03** [comment]
Contact me on discord: AlexDev03#1516
