### ISSUE TITLE
Rejected payments are displayed as correct payments

### ISSUE THREAD

**Issue by liquidman228** [alexdev03/BuyCraftAPI#3]
Encountered an issue where this extension displays rejected payments in the payment top

Here's how you can abuse it:
1. Generate card data using a card generator you can find on the internet
2. Add as many items to your cart as possible so that your donation total is high
3. Try to complete the payment, but you will get an error
4. Now you will be displayed in the top of the top donations.

Please fix this

**Comment by alexdev03** [comment]
Add me on discord please: alexdev03
